#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu
  - echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/ubuntu
  - mkdir -p /home/ubuntu/.ssh
  - chmod 700 /home/ubuntu/.ssh
  - aws ec2 describe-key-pairs --key-name bbc-key --query 'KeyPairs[0].KeyMaterial' --output text > /home/ubuntu/.ssh/bbc-key.pub
  - cat /home/ubuntu/.ssh/bbc-key.pub >> /home/ubuntu/.ssh/authorized_keys
  - chmod 600 /home/ubuntu/.ssh/authorized_keys
  - chown -R ubuntu:ubuntu /home/ubuntu/.ssh

write_files:
  - path: /etc/sudoers.d/ubuntu
    content: |
      ubuntu ALL=(ALL) NOPASSWD:ALL
    owner: root:root
    permissions: '0440'